"""Tool: get_interpretations — previous AI-generated lab result interpretations."""
import json
from typing import Optional
from mcp.server.fastmcp import FastMCP


def register(mcp: FastMCP) -> None:

    @mcp.tool()
    async def get_interpretations(
        user_id: str,
        limit: int = 5,
    ) -> str:
        """
        Return the most recent AI-generated interpretations of the patient's lab results.
        These are detailed analyses previously generated by the system.

        Args:
            user_id: UUID of the patient.
            limit: Number of most recent interpretations to return (default 5).
        """
        from mcp_server.database import get_pg_connection

        conn = await get_pg_connection()
        try:
            rows = await conn.fetch(
                """
                SELECT interpretation_text, completed_at, created_at
                FROM interpretations
                WHERE user_id = $1::uuid AND status = 'completed'
                ORDER BY created_at DESC
                LIMIT $2
                """,
                user_id, limit,
            )
        finally:
            await conn.close()

        interps = [
            {
                "date": (r["completed_at"] or r["created_at"]).isoformat(),
                "text": r["interpretation_text"],
            }
            for r in rows
        ]
        return json.dumps(interps, ensure_ascii=False)


# ─── Stubs for future data sources ────────────────────────────────────────────
# Add new tools here as new patient data types become available:
#
# from mcp_server.tools import notes        → patient self-reported notes / symptoms
# from mcp_server.tools import illness      → documented illness periods
# from mcp_server.tools import fitness      → wearable / fitness tracker data
