"""Tool: get_interpretations — previous AI-generated lab result interpretations."""
import json
from mcp.server.fastmcp import FastMCP

from mcp_server.database import get_pg_pool
from mcp_server.tools._user import resolve_user_id


def register(mcp: FastMCP) -> None:

    @mcp.tool()
    async def get_interpretations(limit: int = 5) -> str:
        """
        Return the most recent AI-generated interpretations of the patient's lab results.
        These are detailed analyses previously generated by the system.

        Args:
            limit: Number of most recent interpretations to return (default 5).
        """
        pool = await get_pg_pool()
        async with pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT interpretation_text, completed_at, created_at
                FROM interpretations
                WHERE user_id = $1::uuid AND status = 'completed'
                ORDER BY created_at DESC
                LIMIT $2
                """,
                resolve_user_id(), limit,
            )

        interps = [
            {
                "date": (r["completed_at"] or r["created_at"]).isoformat(),
                "text": r["interpretation_text"],
            }
            for r in rows
        ]
        return json.dumps(interps, ensure_ascii=False)
